raw-customer-record-url: "https://gist.githubusercontent.com/brianw/19896c50afa89ad4dec3/raw/6c11047887a03483c50017c1d451667fd62a53ca/gistfile1.txt"
reference-latitude: 53.339428
reference-longitude: -6.257664
given-latitude: 52.986375
given-longitude: -6.043701
maximum-distance-in-kilometers: 100
acceptable-float-arithmetic-deviation: 0.1
known-correct-comparison-value: 41.7
